services:
  app:
    image: ghcr.io/vitorhugo-dotnet/jobapplytracker-backend:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: "jdbc:mariadb://mariadb:3306/${DB_NAME}?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
    networks:
      - infra_network
    ports: !reset []

networks:
  infra_network:
    name: infra_network
    external: true
